/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Distri;

import java.util.ArrayList;
import java.util.List;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.io.IOException;
import java.io.ObjectInputStream;



/**
 *
 * @author Ivanlúcio
 */
public class telaP extends javax.swing.JFrame {
    List<Cliente> clientes = new ArrayList<Cliente>();
    List<Pedido> pedidos = new ArrayList<Pedido>();
    
    
    public void addCliente(Cliente cliente){
        clientes.add(cliente);
        
    }
    public List<Cliente> getClientes(){
        return clientes;
        
    }
    
    public void gravaEmArquivo() throws IOException{
        
                ObjectOutputStream out = null;
		ObjectOutputStream o = null;
	
		try{
			out = new ObjectOutputStream(new FileOutputStream("files\\Clientes.txt"));
			o = new ObjectOutputStream(new FileOutputStream("files\\Pedidos.txt"));
			out.writeObject(clientes);
			o.writeObject(pedidos);
			
		}catch(FileNotFoundException e){
			throw new IOException("O arquivo não foi encontrado", e);
		}catch(IOException e){
			throw e;
		}finally{
			if(out!= null){
				out.close();
		   }if(o!= null){
				o.close();
		}

	}
    }
    /**
     * Creates new form telaP
     */
    public telaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        telaP = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cliente = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();
        Entregas = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setSize(new java.awt.Dimension(1280, 960));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/todos-iloveimg-resized (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 570, 980, 100);

        telaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-abstrato-da-malha-do-vetor-pontos-cosmicamente-conectados-e-poligonos-que-voam-no-espaco-restos-voadores-cartao--iloveimg-resized (3).jpg"))); // NOI18N
        telaP.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(telaP);
        telaP.setBounds(0, 0, 1370, 930);

        jMenu1.setText("Cadastro");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        cliente.setText("Clientes");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jMenu1.add(cliente);

        Produtos.setText("Pedidos");
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(Produtos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pesquisar");

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jMenu2.add(Clientes);

        Entregas.setText("Entregas");
        Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregasActionPerformed(evt);
            }
        });
        jMenu2.add(Entregas);

        jMenuBar1.add(jMenu2);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1325, 782));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        // Botão  Sistema - sair
        System.exit(0);
        
    }//GEN-LAST:event_SairMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // Ac
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // Cadastra pedidos
        Pedidos pro = new Pedidos();
        telaP.add(pro);
        pro.setVisible(true);
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // Pesquisa cliente atalho
        PesquisaCliente pes = new PesquisaCliente();
        telaP.add(pes);
        pes.setVisible(true);
    }//GEN-LAST:event_ClientesActionPerformed

    private void EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregasActionPerformed
        // pesquisa entrega atalho
        PesquisaEntrega pes = new PesquisaEntrega();
        telaP.add(pes);
        pes.setVisible(true);
    }//GEN-LAST:event_EntregasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // maximizar tela principal
        
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // Tcessar tela de cadastro - clientes
        Clientes cli = new Clientes();
        telaP.add(cli);
        cli.setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Entregas;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel telaP;
    // End of variables declaration//GEN-END:variables

   
        
}
